const plans={strength:{name:'Strength',rate:8000},cardio:{name:'Strength + Cardio',rate:12000},complete:{name:'Strength + Cardio + Sauna',rate:18000}};
const durations=[1,3,6,12];let months=1;
const format=n=>new Intl.NumberFormat('en-PK').format(n);
const dialog=document.querySelector('#enquiry'),form=document.querySelector('#enquiry-form'),status=document.querySelector('#form-status');
function setDuration(value){if(!durations.includes(value))throw new Error('Choose 1, 3, 6 or 12 months.');months=value;document.querySelectorAll('[data-months]').forEach(b=>{const on=Number(b.dataset.months)===value;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});document.querySelectorAll('[data-price]').forEach(p=>p.textContent=format(Number(p.dataset.price)*months));document.querySelectorAll('.period').forEach(p=>p.textContent=`Total for ${months} ${months===1?'month':'months'}`);}
document.querySelectorAll('[data-months]').forEach(b=>b.addEventListener('click',()=>setDuration(Number(b.dataset.months))));
function updateTotal(){const plan=plans[form.elements.plan.value],duration=Number(form.elements.months.value);document.querySelector('#form-total').textContent=plan?`PKR ${format(plan.rate*duration)}`:'General enquiry';form.elements.months.disabled=!plan;}
function openEnquiry(plan){if(plan!=='general'&&!plans[plan])throw new Error('Unknown membership.');form.elements.plan.value=plan;form.elements.months.value=String(months);status.textContent='';document.querySelector('#copy-fallback').hidden=true;updateTotal();dialog.showModal();document.body.classList.add('dialog-open');}
document.querySelectorAll('.choose-plan').forEach(b=>b.addEventListener('click',()=>openEnquiry(b.dataset.plan)));
document.querySelector('#general-enquiry').addEventListener('click',()=>openEnquiry('general'));
document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>document.body.classList.remove('dialog-open'));
form.elements.plan.addEventListener('change',updateTotal);form.elements.months.addEventListener('change',updateTotal);
function enquiryDetails(){const data=new FormData(form),plan=plans[data.get('plan')],duration=Number(data.get('months'));return `H1 FITNESS CLUB — ${plan?'MEMBERSHIP REQUEST':'GENERAL ENQUIRY'}\n\nName: ${String(data.get('name')).trim()}\nPhone: ${String(data.get('phone')).trim()}\nEmail: ${String(data.get('email')).trim()}\n\n${plan?`Package: ${plan.name}\nDuration: ${duration} ${duration===1?'month':'months'}\nMonthly price: PKR ${format(plan.rate)}\nTotal: PKR ${format(plan.rate*duration)}\n`:'Request: General information\n'}\nMessage: ${String(data.get('message')||'No additional message').trim()}\n\nPlease contact me with the next steps. This is an enquiry, not a completed payment.`;}
form.addEventListener('submit',e=>{e.preventDefault();const plan=plans[form.elements.plan.value];const subject=`H1 Fitness Club — ${plan?plan.name+' membership request':'General enquiry'}`;window.location.href=`mailto:h1fitness10@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(enquiryDetails())}`;status.textContent='Your email draft is ready to open. Send it from your email app to contact H1 Fitness Club. If no app opens, copy your enquiry below and email it to h1fitness10@gmail.com.';});
document.querySelector('#copy-enquiry').addEventListener('click',async()=>{if(!form.reportValidity())return;const text=enquiryDetails();try{await navigator.clipboard.writeText(text);status.textContent='Copied. Paste these details into an email to h1fitness10@gmail.com.';}catch{const box=document.querySelector('#copy-fallback');box.hidden=false;box.value=text;box.focus();box.select();status.textContent='Select and copy the enquiry text below, then email it to h1fitness10@gmail.com.';}});
document.querySelector('#year').textContent=String(new Date().getFullYear());
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_membership_enquiry',description:'Select a membership duration and open the enquiry form. Does not send an email or complete a purchase.',inputSchema:{type:'object',properties:{plan:{type:'string',enum:['strength','cardio','complete']},months:{type:'integer',enum:[1,3,6,12]}},required:['plan','months'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!plans[input.plan]||!durations.includes(input.months))throw new Error('Invalid membership or duration.');setDuration(input.months);if(dialog.open)dialog.close();openEnquiry(input.plan);return{plan:plans[input.plan].name,months,total:plans[input.plan].rate*months,currency:'PKR',emailSent:false};}})).catch(()=>{});}catch{}}